# Generated by Django 6.0.5 on 2026-05-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("record_app", "0003_privateconversation_privatemessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="messages/"),
        ),
        migrations.AddField(
            model_name="privatemessage",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="private_messages/"
            ),
        ),
    ]
