# Generated by Django 6.0.5 on 2026-05-13 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("record_app", "0004_message_image_privatemessage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="audio",
            field=models.FileField(blank=True, null=True, upload_to="messages_audio/"),
        ),
        migrations.AddField(
            model_name="privatemessage",
            name="audio",
            field=models.FileField(
                blank=True, null=True, upload_to="private_messages_audio/"
            ),
        ),
    ]
