# Generated by Django 6.0.4 on 2026-05-25 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("record_app", "0005_message_audio_privatemessage_audio"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
    ]
