# Generated by Django 6.0.4 on 2026-05-25 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("record_app", "0006_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_banned",
            field=models.BooleanField(default=False),
        ),
    ]
